imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.ini }

framework:
    test: ~
    csrf_protection: false
    session:
        storage_id: session.storage.filesystem
        name: test

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
