security:
    # acl:
    #   connection: default
    #   tables:
    #       class: acl_classes
    #       entry: acl_entries
    #       object_identity: acl_obj_ids
    #       object_identity_ancestors: acl_obj_id_ancestors
    #       security_identity: acl_security_identities
    
    encoders:
        Core\Library\EntityBundle\Entity\User: 
            algorithm: sha512
            iterations: 1
            encode-as-base64: false

    #role_hierarchy:
    #     ROLE_ADMIN:       ROLE_USER
    #     ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        core_users:
            entity: { class: Core\Library\EntityBundle\Entity\User, property: username }

    factories:
        - "%kernel.root_dir%/../src/Core/Security/RestSecurityBundle/Resources/config/security_factories.xml"

    firewalls:
        rest:
            pattern: ^/
            rest_auth: true
            stateless: true

    access_control:
         - { path: ^/time, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: [ROLE_USER_MOBILE, ROLE_USER_ADMIN] }
       
        
        